apiVersion: v1
kind: Service
metadata:
  name: media-intelligence-service
  namespace: media-platform
spec:
  selector:
    app: media-intelligence-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
